
package password;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author danyx25
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void limpiarContraseña (){
        txtRegistroContraseña.setText("");
        txtRegistroConfirmarContraseña.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRegistroUsuario = new javax.swing.JTextField();
        txtRegistroContraseña = new javax.swing.JTextField();
        txtRegistroConfirmarContraseña = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 24, 24));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirmar Contraseña:");

        txtRegistroUsuario.setBackground(new java.awt.Color(25, 24, 24));
        txtRegistroUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRegistroUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtRegistroUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtRegistroContraseña.setBackground(new java.awt.Color(25, 24, 24));
        txtRegistroContraseña.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRegistroContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtRegistroContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtRegistroConfirmarContraseña.setBackground(new java.awt.Color(25, 24, 24));
        txtRegistroConfirmarContraseña.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRegistroConfirmarContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtRegistroConfirmarContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        btnRegistrar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password/imagenes/regitrarse (1).png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtRegistroUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtRegistroContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegistroConfirmarContraseña))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtRegistroContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRegistroConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 550, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //METODO PARA ENVIAR A LA BASE DE DATOS
    int aux=0;
    public boolean Guardarbd(){
         boolean registrar = false;
        //INTEFAZ DE ACCESO A LA BASE DE DATOS
        Statement stm = null;
        //CONEXION CON LA BASE DE DATOS
        Connection con = null;
        String sql;
        //SENTENCIA SQL
        String a=txtRegistroUsuario.getText();
        String b=txtRegistroContraseña.getText();
        sql="INSERT INTO `gestionPassword`.`Datos`(`Usuario`,`Contraseña`)values('"+a+"','"+b+"');";
        try {
            //ES UNA INSTANCIA DE LA CONEXION PREVIAMENTE CREADA
            aux=0;
            Password conexion = new Password();
            con = conexion.conectarBaseDatos();
            stm = con.createStatement();
            stm.execute(sql);
            registrar = true;
            stm.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR - Este Usuario ya se encuentra Registrado,\nIngrese otro Nombre de Usuario", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.getMessage());
            txtRegistroUsuario.setText("");
            limpiarContraseña();
            txtRegistroUsuario.requestFocus();
            aux=1;
        }
        return registrar;
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(txtRegistroUsuario.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "ERROR - Necesitar Ingresar un Nombre de Usuario", "ERROR", JOptionPane.ERROR_MESSAGE);
             txtRegistroUsuario.requestFocus();
             return;
        }
        if(txtRegistroContraseña.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "ERROR - Necesitar Ingresar una Contraseña", "ERROR", JOptionPane.ERROR_MESSAGE);
             txtRegistroContraseña.requestFocus();
             return;
        }
       
        if(txtRegistroConfirmarContraseña.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "ERROR - Necesitar Ingresar la Confirmación de la Contraseña", "ERROR", JOptionPane.ERROR_MESSAGE);
             txtRegistroConfirmarContraseña.requestFocus();
             return;
        }
        if(txtRegistroContraseña.getText().equals(txtRegistroConfirmarContraseña.getText())){
            Guardarbd();
            if(aux==0){
                JOptionPane.showMessageDialog(rootPane,"Gracias por Registrarte.");
                new Interfaz().setVisible(true);
                this.dispose();
            }else{
                return;
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "ERROR - Las Contraseñas no coinciden", "ERROR", JOptionPane.ERROR_MESSAGE);
             limpiarContraseña();
             txtRegistroContraseña.requestFocus();
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRegistroConfirmarContraseña;
    private javax.swing.JTextField txtRegistroContraseña;
    private javax.swing.JTextField txtRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
